spring.application.name=Harsh Task App

# Point to your new database
spring.datasource.url=jdbc:mysql://localhost:3306/task_tracker_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=harsh231104

# Since you already created the table manually, tell Spring to just validate it exists
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

